# use java support.
language: java
jdk:
  - openjdk11
  
# run in container.
sudo: false

services:
  - xvfb
# use linux as operating system.
os:
  - linux

# imitate a display for RunWithFX tests
before_script:
  - export DISPLAY=:99.0
  - sleep 3
  
# run maven build.
script:
  - ./gradlew build

cache:
  directories:
  - $HOME/.gradle/caches/
  
#deploy:
#  provider: script
#  script: bash .ci/publish.sh
#  skip_cleanup: true
#  on:
#    tags: true
